- Get your DingTalk number (write it manually to notebook) and split into sequence of three-digit numbers. The tail with one two-digit number should be discarded. For example for ID=12345678900 this code should return sequence [123, 456, 789].  

In [5]:
import numpy as np

numbers = [767,293,861]
print(numbers)
print(type(numbers))
print(type(number[0]))

[767, 293, 861]
<class 'list'>
<class 'int'>


- Convert this sequence of numbers into 3x3 numpy matrix A where each element of previous array is a row and one digit of each number is a column. For example, for this sequence [123, 456, 789] the matrix will be equal to [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
A = np.zeros((3,3), dtype = int)

for i in range(0,3):
  num = numbers[i]
  for j in range(2,-1,-1):
    tmp = num%10
    num = num/10
    A[i][j] = tmp

print(A)
print(type(A))

[[7 6 7]
 [2 9 3]
 [8 6 1]]
<class 'numpy.ndarray'>


- Read the NumPy documentation and compute the reversed matrix A (if you can reverse it), transposed matrix A, multiplication of matrix A and matrix A^(-1) or matrix A and transposed A, create a submatrix consists of the first and third rows of matrix A

In [13]:
reversed_matrix = np.linalg.inv(A)
print(reversed_matrix)

transposed_matrix = A.T
print(transposed_matrix)

multiplication = np.dot(A,reversed_matrix)
print(multiplication)

submatrix = A[[0,2],:]
print(submatrix)

[[ 0.02564103 -0.1025641   0.12820513]
 [-0.06267806  0.13960114  0.01994302]
 [ 0.17094017 -0.01709402 -0.14529915]]
[[7 2 8]
 [6 9 6]
 [7 3 1]]
[[ 1.00000000e+00  6.24500451e-17 -1.38777878e-16]
 [-5.55111512e-17  1.00000000e+00 -2.77555756e-17]
 [-2.77555756e-17  1.04083409e-16  1.00000000e+00]]
[[7 6 7]
 [8 6 1]]
